package IHM;

import Utility.BibalExceptions;
import Utility.ModelTableau;
import control.EmpruntControl;
import control.ExemplaireControl;
import entite.Exemplaire;
import entite.Livre;
import entite.Magazine;
import entite.Oeuvre;

import static Utility.Utility.showMessageSucces;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import static javax.swing.JOptionPane.showConfirmDialog;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
/**
 * 
 * @author Diallo & Janati
 */
public class GestionExemplaires extends javax.swing.JDialog implements MouseListener {

    public GestionExemplaires(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tableExemplaires.addMouseListener(this);
        tableExemplaires.addMouseListener(this);
        tableExemplaires.setModel(new ModelTableau(new Object[0][0],
                new String[]{"ID", "Etat"}));
        tableExemplaires.setRowHeight(30);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/bibliotheque_icone.png")));
    }

    /**
     * @wbp.parser.constructor
     */
    public GestionExemplaires(java.awt.Frame parent, boolean modal,
            Oeuvre oeuvre) {
        this(parent, modal);

        identifiantLabelValue.setText(oeuvre.getId() + "");
        titreLabelValue.setText(oeuvre.getTitre());
        categorieLabelValue.setText(oeuvre.getCategorie());
        typeOeuvreLabelValue.setText(oeuvre.getClass().getSimpleName());
        auteurLabelValue.setText(oeuvre.getAuteur());
        nbExemplaireLabelValue.setText(oeuvre.getExamplairesOeuvre().size() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panAjoutOeuvre = new javax.swing.JPanel();
        pan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        typeOeuvreLabel = new javax.swing.JLabel();
        identifiantLabel = new javax.swing.JLabel();
        auteurLabel = new javax.swing.JLabel();
        titreLabel = new javax.swing.JLabel();
        categorieLabel = new javax.swing.JLabel();
        nbExemplaire = new javax.swing.JLabel();
        identifiantLabelValue = new javax.swing.JLabel();
        identifiantLabelValue.setForeground(new Color(255, 255, 128));
        titreLabelValue = new javax.swing.JLabel();
        titreLabelValue.setForeground(new Color(255, 255, 128));
        categorieLabelValue = new javax.swing.JLabel();
        categorieLabelValue.setForeground(new Color(255, 255, 128));
        typeOeuvreLabelValue = new javax.swing.JLabel();
        typeOeuvreLabelValue.setForeground(new Color(255, 255, 128));
        auteurLabelValue = new javax.swing.JLabel();
        auteurLabelValue.setForeground(new Color(255, 255, 128));
        nbExemplaireLabelValue = new javax.swing.JLabel();
        nbExemplaireLabelValue.setForeground(new Color(255, 255, 128));
        jPanel3 = new javax.swing.JPanel();
        ajouterButton = new javax.swing.JButton();
        modifierButton = new javax.swing.JButton();
        retirerButton = new javax.swing.JButton();
        afficherButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        panExemplaires = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableExemplaires = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Exemplaire");
        setResizable(false);

        jPanel1.setBackground(new Color(98, 189, 187));
        jPanel1.setName("Gestion personnel"); // NOI18N
        jPanel1.setPreferredSize(new Dimension(1162, 639));
        jPanel1.setRequestFocusEnabled(false);

        panAjoutOeuvre.setBackground(new java.awt.Color(255, 255, 255));

        pan.setBackground(new Color(98, 189, 187));
        pan.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new Color(98, 189, 187));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        typeOeuvreLabel.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        typeOeuvreLabel.setForeground(new Color(255, 255, 255));
        typeOeuvreLabel.setText("Type de l'oeuvre");

        identifiantLabel.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        identifiantLabel.setForeground(new Color(255, 255, 255));
        identifiantLabel.setText("Identifiant ");

        auteurLabel.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        auteurLabel.setForeground(new Color(255, 255, 255));
        auteurLabel.setText("Auteur");

        titreLabel.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        titreLabel.setForeground(new Color(255, 255, 255));
        titreLabel.setText("Titre");

        categorieLabel.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        categorieLabel.setForeground(new Color(255, 255, 255));
        categorieLabel.setText("Catégorie");

        nbExemplaire.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        nbExemplaire.setForeground(new Color(255, 255, 255));
        nbExemplaire.setText("Nombre \nd'exemplaire");

        identifiantLabelValue.setFont(new Font("Century Gothic", Font.BOLD, 20)); // NOI18N
        identifiantLabelValue.setText("1");

        titreLabelValue.setFont(new Font("Century Gothic", Font.BOLD, 18)); // NOI18N
        titreLabelValue.setText("1");

        categorieLabelValue.setFont(new Font("Century Gothic", Font.BOLD, 16)); // NOI18N
        categorieLabelValue.setText("1");

        typeOeuvreLabelValue.setFont(new Font("Century Gothic", Font.BOLD, 16)); // NOI18N
        typeOeuvreLabelValue.setText("1");

        auteurLabelValue.setFont(new Font("Century Gothic", Font.BOLD, 14)); // NOI18N
        auteurLabelValue.setText("1");

        nbExemplaireLabelValue.setFont(new Font("Century Gothic", Font.BOLD, 16)); // NOI18N
        nbExemplaireLabelValue.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(nbExemplaire)
        					.addGap(55)
        					.addComponent(nbExemplaireLabelValue))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(typeOeuvreLabel))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGap(4)
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(identifiantLabel)
        								.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(titreLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(categorieLabel, GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(auteurLabel)))
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGap(54)
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(titreLabelValue)
        								.addComponent(auteurLabelValue)
        								.addComponent(categorieLabelValue)
        								.addComponent(typeOeuvreLabelValue)))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGap(79)
        							.addComponent(identifiantLabelValue)))))
        			.addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(identifiantLabel)
        				.addComponent(identifiantLabelValue))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(titreLabel)
        				.addComponent(titreLabelValue))
        			.addGap(30)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(categorieLabel)
        				.addComponent(categorieLabelValue))
        			.addGap(42)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(typeOeuvreLabel)
        				.addComponent(typeOeuvreLabelValue))
        			.addGap(28)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(auteurLabel)
        				.addComponent(auteurLabelValue))
        			.addGap(33)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(nbExemplaire)
        				.addComponent(nbExemplaireLabelValue))
        			.addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBackground(new Color(98, 189, 187));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ajouterButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ajouterButton.setText("Ajouter");
        ajouterButton.setPreferredSize(new java.awt.Dimension(95, 31));
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        modifierButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        modifierButton.setText("Modifier");
        modifierButton.setEnabled(false);
        modifierButton.setPreferredSize(new java.awt.Dimension(95, 31));
        modifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierButtonActionPerformed(evt);
            }
        });

        retirerButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        retirerButton.setText("Retirer");
        retirerButton.setEnabled(false);
        retirerButton.setPreferredSize(new java.awt.Dimension(95, 31));
        retirerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirer(evt);
            }
        });

        afficherButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        afficherButton.setText("Afficher");
        afficherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher(evt);
            }
        });

        annulerButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(ajouterButton, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        				.addComponent(afficherButton, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        				.addComponent(modifierButton, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        				.addComponent(retirerButton, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        				.addComponent(annulerButton, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(ajouterButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(afficherButton)
        			.addGap(18)
        			.addComponent(modifierButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(retirerButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(annulerButton)
        			.addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        panExemplaires.setBackground(new Color(98, 189, 187));
        panExemplaires.setBorder(javax.swing.BorderFactory.createTitledBorder("Exemplaires"));

        jScrollPane2.getViewport().setBackground(Color.white);
        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tableExemplaires.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Etat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExemplaires.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableExemplaires.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableExemplaires);

        javax.swing.GroupLayout panExemplairesLayout = new javax.swing.GroupLayout(panExemplaires);
        panExemplairesLayout.setHorizontalGroup(
        	panExemplairesLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panExemplairesLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
        );
        panExemplairesLayout.setVerticalGroup(
        	panExemplairesLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );
        panExemplaires.setLayout(panExemplairesLayout);

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        panLayout.setHorizontalGroup(
        	panLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panLayout.createSequentialGroup()
        			.addGap(3)
        			.addGroup(panLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panLayout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        					.addGap(2))
        				.addGroup(panLayout.createSequentialGroup()
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(5)
        					.addComponent(panExemplaires, GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))))
        );
        panLayout.setVerticalGroup(
        	panLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)
        			.addGap(31)
        			.addGroup(panLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(panExemplaires, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(2))
        );
        pan.setLayout(panLayout);

        javax.swing.GroupLayout panAjoutOeuvreLayout = new javax.swing.GroupLayout(panAjoutOeuvre);
        panAjoutOeuvreLayout.setHorizontalGroup(
        	panAjoutOeuvreLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(pan, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        panAjoutOeuvreLayout.setVerticalGroup(
        	panAjoutOeuvreLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panAjoutOeuvreLayout.createSequentialGroup()
        			.addComponent(pan, GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        			.addContainerGap())
        );
        panAjoutOeuvre.setLayout(panAjoutOeuvreLayout);

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLabel.setForeground(new Color(255, 255, 255));
        titleLabel.setText("information du livre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panAjoutOeuvre, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap(158, Short.MAX_VALUE)
        			.addComponent(titleLabel, GroupLayout.PREFERRED_SIZE, 431, GroupLayout.PREFERRED_SIZE)
        			.addGap(86))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(titleLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(panAjoutOeuvre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        Oeuvre oeuvre = getOeuvreInfos();
        if (null != oeuvre) {
            AjoutExemplaire ajoutExemplaire = new AjoutExemplaire(null, true, oeuvre);
            ajoutExemplaire.setLocationRelativeTo(null);
            ajoutExemplaire.setVisible(true);
        }
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void modifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierButtonActionPerformed

        Exemplaire exemplaire = getExempalireInfos();
        if (null != exemplaire) {
            ModificationExemplaire modificationExemplaire
                    = new ModificationExemplaire(null, true, exemplaire);
            modificationExemplaire.setLocationRelativeTo(null);
            modificationExemplaire.setVisible(true);
        }
    }//GEN-LAST:event_modifierButtonActionPerformed

    private void afficher(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher
        try {
            Oeuvre oeuvre = getOeuvreInfos();
            ArrayList<Exemplaire> listExemplaires = ExemplaireControl.find(oeuvre);
            if (null != listExemplaires) {
                fillExemplaireJtable(listExemplaires);
            } else {
                showMessageSucces("Aucun exemplaire trouvé");
            }

        } catch (BibalExceptions e) {
            System.out.println("IHM.GestionOeuvre.afficherButtonActionPerformed()");
        }
    }//GEN-LAST:event_afficher

    private void retirer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirer
        String message = "\nSupprimer cet exempalaire ?\n"
                + "Cela supprimera aussi tous les emprunts de cet exemplaire\n";

        int reponse = showConfirmDialog(null, message,
                "Avertissement", JOptionPane.OK_CANCEL_OPTION);
        if (reponse == JOptionPane.OK_OPTION) {
            try {
                Exemplaire exemplaire = getExempalireInfos();
                if (null != exemplaire) {
                    EmpruntControl.supprimer(exemplaire);
                    ExemplaireControl.supprimer(exemplaire);
                    ((ModelTableau) tableExemplaires.getModel()).removeRow(tableExemplaires.getSelectedRow());
                    showMessageSucces("L'exemplaire a bien été supprimée");
                    modifierButton.setEnabled(false);
                    retirerButton.setEnabled(false);
                }

            } catch (BibalExceptions ex) {
                System.out.println("IHM.Exemplaires.retirerButtonActionPerformed()" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_retirer

    private Oeuvre getOeuvreInfos() {
        int id = Integer.parseInt(identifiantLabelValue.getText());
        String titre = titreLabelValue.getText();
        String auteur = auteurLabelValue.getText();
        String categorie = categorieLabelValue.getText();
        String typeOeuvre = typeOeuvreLabelValue.getText();
        Oeuvre oeuvre;
        if (typeOeuvre.equals(Magazine.class.getSimpleName())) {
            oeuvre = new Magazine(id, titre, auteur, categorie);
        } else {
            oeuvre = new Livre(id, titre, auteur, categorie);
        }
        return oeuvre;
    }

    private Exemplaire getExempalireInfos() {
        int id = Integer.parseInt(dataLigneSelected[0].toString());
        String etatExemplaire = dataLigneSelected[1].toString();
        return new Exemplaire(id, etatExemplaire);
    }

    private void fillExemplaireJtable(ArrayList<Exemplaire> listExemplaires) {
        String titre[] = new String[]{"ID", "Etat"};
        if (listExemplaires.size() > 0) {
//            pour le findByID si l'objet ajouté est null
            int nbLigne = (null == listExemplaires.get(0)) ? 0 : listExemplaires.size();
            Object data[][] = new Object[nbLigne][titre.length];
            for (int i = 0; i < nbLigne; i++) {
                Exemplaire exemplaire = listExemplaires.get(i);
                data[i][0] = exemplaire.getId();
                data[i][1] = exemplaire.getEtat();
            }
            ModelTableau model = new ModelTableau(data, titre);
            tableExemplaires.setModel(model);
            tableExemplaires.setRowHeight(30);
        } else {
            //afficher tableau vide
            Object data[][] = new Object[1][titre.length];
            ModelTableau model = new ModelTableau(data, titre);
            tableExemplaires.setModel(model);
            tableExemplaires.setRowHeight(1);
        }
        modifierButton.setEnabled(false);
        retirerButton.setEnabled(false);
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        int row = tableExemplaires.getSelectedRow();
        int nbreCol = tableExemplaires.getColumnCount();

        dataLigneSelected = new Object[nbreCol];
        if (row >= 0) {
            for (int i = 0; i < nbreCol; i++) {
                dataLigneSelected[i] = tableExemplaires.getModel().getValueAt(row, i);
            }
            modifierButton.setEnabled(true);
            retirerButton.setEnabled(true);
        } else {
            modifierButton.setEnabled(false);
            retirerButton.setEnabled(false);
        }
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    public static void setNbExemplaireLabelValue(String value) {
        GestionExemplaires.nbExemplaireLabelValue.setText(value);
    }

    public static String getNbExemplaireLabelValue() {
        return nbExemplaireLabelValue.getText();
    }

    private Object dataLigneSelected[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficherButton;
    private javax.swing.JButton ajouterButton;
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel auteurLabel;
    private javax.swing.JLabel auteurLabelValue;
    private javax.swing.JLabel categorieLabel;
    private javax.swing.JLabel categorieLabelValue;
    private javax.swing.JLabel identifiantLabel;
    private javax.swing.JLabel identifiantLabelValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifierButton;
    private javax.swing.JLabel nbExemplaire;
    private static javax.swing.JLabel nbExemplaireLabelValue;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel panAjoutOeuvre;
    private javax.swing.JPanel panExemplaires;
    private javax.swing.JButton retirerButton;
    public static javax.swing.JTable tableExemplaires;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JLabel titreLabelValue;
    private javax.swing.JLabel typeOeuvreLabel;
    private javax.swing.JLabel typeOeuvreLabelValue;
    // End of variables declaration//GEN-END:variables
}
